### ISSUE TITLE
Poner los schemas en directorio local

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/sorting_hat_step#56]
También actualizar APF para acceder al schemaless consumer

Considerar test de integración usando schemaless consumer
- generar mensaje sin schema
- correr el step con schemaless consumer

**Comment by AlxEnashi** [comment]
- [ ] Agregar carpeta pra los cosumer schemas.
- [ ] Agregar a los settings del consumer el path del schema (opcional) Solo se lee si el comsumer es schemaless
- [ ] Testear (integracion) el step con un schemaless conusmer 

Para testear lo complejo:
 - No sabemos como generar mensajes **avro** sin schema
Como testear:
- Generar mensajes de avros sin schema
- Llenar el topico de test del kafka de test con los mensajes
- Crear un step que use consumer schemaless
- Correr start en test
- Asserts sobre el topico de salida u otras cosas.

**Comment by dirodriguezm** [comment]
Schemas de elasticc https://github.com/LSSTDESC/elasticc/blob/main/alert_schema/elasticc.v0_9_1.alert.avsc
